### PR TITLE
Add documentation

### PR DESCRIPTION
**Pull request by natemcmaster**
Wrote some docs to answer questions I get asked most often.

cc @bricelam @rowanmiller

### CODE REVIEW

**Comment by natemcmaster** [comment]
Ping

**Comment by bricelam** [comment]
Maybe this should go on the wiki for now...

**Comment by natemcmaster** [comment]
It's already there. Reason for adding here is that wiki = docs graveyard.

**Comment by rowanmiller** [comment]
I doubt this will be any less of a graveyard than the wiki 😄. There isn't much content here, so I would probably just inline it all in the README.

**Pull request closed without merging**
