### PR TITLE
Fix non-Windows dotnet build

### PR DESCRIPTION
**Pull request by natemcmaster**
cc @victorhurdugaci @bricelam 

KoreBuild tries to restore/build our test UWP app...does not work on xplat for obivous reasons.

### CODE REVIEW

**Comment by bricelam** [comment]
Would renaming the `project.json` to `Microsoft.Data.Sqlite.FunctionalTests.UWP.project.json` work?

**Comment by natemcmaster** [comment]
Yup, let's do that. I didn't know VS tooling would still recognize `<project name>.project.json`.

**Comment by bricelam** [comment]
Oh what knowledge you can gain from spelunking MSBuild scripts! :wink:

**Comment by bricelam** [comment]
:shipit:

**Comment by natemcmaster** [comment]
Depends on https://github.com/aspnet/Universe/pull/365

**Comment by victorhurdugaci** [comment]
This will also be fixable when this goes in https://github.com/aspnet/Universe/issues/360

**Comment by victorhurdugaci** [comment]
But that should be okay as long as your build system understands different names other than `project.json`

**Comment by natemcmaster** [comment]
In this case, we want CI build system to skip the UWP test project but VS to still work.

**Pull request merged**
