### PR TITLE
Improve error message for common misuse of SqliteParameter

### PR DESCRIPTION
**Pull request by natemcmaster**
See #209

### CODE REVIEW

**Comment by natemcmaster** [comment]
Ping on this old PR @bricelam

**Comment by bricelam** [comment]
This feels unnecessary to me. We're honoring the ADO.NET contract, I don't think we need to defend that because SQLite.NET didn't.

**Comment by divega** [comment]
I can go either way re having a custom exception for this, but I like the `nameof()` change :smile:

**Comment by natemcmaster** [comment]
Going over old PRs...can't remember the original motivation for this anymore.

**Pull request closed without merging**
