### PR TITLE
Copy sqlite3.dll when using packages.config

### LINKED ISSUE #134: Unable to load DLL 'sqlite3' when using packages.config
Because NuGet only copies runtime artifacts when using `project.json`, if you try to use the package on a project using `packages.config`, you'll get the following error.

> Unable to load DLL 'sqlite3': The specified module could not be found. (Exception from HRESULT: 0x8007007E)

We might be able to make this work using MSBuild scripts...

### PR DESCRIPTION
**Pull request by bricelam**
Resolves #134

### CODE REVIEW

**Comment by davidfowl** [comment]
Tricky, won't this collide with the default msbuild logic to copy native assets?

**Comment by bricelam** [comment]
It only kicks in if `project.json` is present. This only runs if it's not. :wink:

**Comment by davidfowl** [comment]
ah hah!

**Comment by bricelam** [comment]
...and only on net451 projects.

**Comment by natemcmaster** [comment]
:shirt: :it:

**Comment by bricelam** [comment]
Recalling. I had to rework this a bit for #128.

**Pull request closed without merging**
