### PR TITLE
React to changes in dnx runtime services

### PR DESCRIPTION
**Pull request by natemcmaster**

### CODE REVIEW

**Comment by anpete** [comment]
:shipit:

**Comment by davidfowl** [comment]
Instead use the clr type RuntimeInformation

**Comment by natemcmaster** [comment]
@davidfowl  Do stable packages (`4.0.0`, no star) exist for System.Runtime.InteropServices.RuntimeInformation? We had to work around this in the past https://github.com/aspnet/Microsoft.Data.Sqlite/pull/123

**Comment by natemcmaster** [comment]
Checked...RuntimeInformation will not work for us due to packaging issues. Sticking with this implementation. It will be removed anyways once NuGet supports native binaries.

**Pull request merged**
