### PR TITLE
Disable API Check in a project with untracked breaking changes

### PR DESCRIPTION
**Pull request by dougbu**

### CODE REVIEW

**Comment by dougbu** [comment]
Will go in before fix for aspnet/KoreBuild#143

**Comment by bricelam** [comment]
Oh man, I tried so hard to stay on top of that and write them by hand in the interim...

**Comment by dougbu** [comment]
See aspnet/BuildTools#205 for more context

**Comment by dougbu** [comment]
And we have a winner @bricelam !

**Comment by dougbu** [comment]
fe63a2a

**Pull request closed without merging**
