### PR TITLE
Revert to SQLite 3.12.3

### PR DESCRIPTION
**Pull request by natemcmaster**
Reverses https://github.com/aspnet/Microsoft.Data.Sqlite/pull/301
Fixes https://github.com/aspnet/EntityFramework/issues/7040

cc @bricelam

### CODE REVIEW

**Comment by bricelam** [comment]
@rowanmiller @divega Did we want to do this in 1.1.1 as well?

**Comment by rowanmiller** [comment]
Yes I think so. Wait for @divega to confirm though.

**Comment by divega** [comment]
I think so too, unless there is any bad problem with 3.12.3 that 3.13.0 fixed.

**Comment by divega** [comment]
Created the milestone and assigned this to it.

**Comment by divega** [comment]
I asked @smitpatel to create the 1.1.1 branch and pick this PR.

**Comment by natemcmaster** [comment]
There were 2 changes in SQLite 3.13.0 package - 1 the new package layout, 2 - upgrading to SQLite 3.13. Here are the release notes from sqlite itself https://sqlite.org/changes.html#version_3_13_0.

**Pull request merged**
