### PR TITLE
Implement SqliteCommand.Prepare

### PR DESCRIPTION
**Pull request by AlexanderTaeschner**
New try to implement SqliteCommand.Prepare.

Compared to #334 the following additional changes where made:
- connections are explicitly closed and debug builds throw an exception, so that the existence of undisposed statements can be tracked
- in ExecuteReader statements are disposed before binding related exceptions are thrown, so that the connection can be closed safely afterwards
- disallow a second open data reader or changes to CommandText or Connection while an reader is open
- since the disposal of commands did not always dispose all statements in the EF test suite, added a list of all statements associated to a connection and dispose them excpilictly before trying to close the connection

Addresses #235.

### CODE REVIEW

**Comment by AlexanderTaeschner** [comment]
Inspired by the benchmark refered to in #235, I have redone the described insert test of 100000 values with this patch:

```
 |                                Method |       Mean |     Error |    StdDev |     Median |
 |-------------------------------------- |-----------:|----------:|----------:|-----------:|
 |    InsertSpeed_Prepared_NoTransaction |   499.6 ms | 11.935 ms | 32.873 ms |   485.4 ms |
 |    InsertSpeed_Prepared_InTransaction |   245.7 ms |  2.791 ms |  2.474 ms |   245.0 ms |
 | InsertSpeed_NotPrepared_NoTransaction | 1,129.4 ms | 20.718 ms | 18.366 ms | 1,121.4 ms |
 | InsertSpeed_NotPrepared_InTransaction |   887.2 ms | 17.695 ms | 23.009 ms |   887.6 ms |
```

Where the methods are:
- InsertSpeed_Prepared_NoTransaction: use prepared statements and rebind the parameters for each insert
- InsertSpeed_Prepared_InTransaction: use prepared statements inside a transaction and rebind the parameters for each insert
- InsertSpeed_NotPrepared_NoTransaction: change CommandText for each insert
- InsertSpeed_NotPrepared_InTransaction: change CommandText for each insert; the loop runs inside a transaction

The benchmark code can be found here:
https://github.com/AlexanderTaeschner/MicrosoftDataSqliteBenchmarking/blob/master/InsertTest/Program.cs

**Comment by AlexanderTaeschner** [comment]
Out of curiosity I added the same tests using the System.Data.SQLite library. 
In the following table the results are presented (SDS marks the tests run against System.Data.SQLite and
MDS the ones using Microsoft.Data.Sqlite). The benchmark runs were done on a faster PC than the ones presented above, so don't wonder that the times are different to the other table!

```
 |                                    Method |     Mean |      Error |     StdDev |
 |------------------------------------------ |---------:|-----------:|-----------:|
 |    InsertSpeed_MDS_Prepared_NoTransaction | 225.2 ms |  1.5993 ms |  1.4177 ms |
 |    InsertSpeed_SDS_Prepared_NoTransaction | 248.4 ms |  1.1239 ms |  1.0513 ms |
 |    InsertSpeed_MDS_Prepared_InTransaction | 109.6 ms |  1.7031 ms |  1.4222 ms |
 |    InsertSpeed_SDS_Prepared_InTransaction | 126.7 ms |  1.0315 ms |  0.9648 ms |
 | InsertSpeed_MDS_NotPrepared_NoTransaction | 515.7 ms | 11.5907 ms | 13.7979 ms |
 | InsertSpeed_SDS_NotPrepared_NoTransaction | 623.4 ms |  2.3741 ms |  2.2207 ms |
 | InsertSpeed_MDS_NotPrepared_InTransaction | 359.3 ms |  0.8317 ms |  0.6493 ms |
 | InsertSpeed_SDS_NotPrepared_InTransaction | 435.4 ms |  3.4132 ms |  3.1927 ms |
```

The MDS runs are slightly faster than SDS :)

**Comment by bricelam** [comment]
Hey @AlexanderTaeschner, sorry I've been unresponsive. We're trying to get everything code complete for 2.0.0 so we can get a good, beta-quality release out. The corresponding issue for this PR was triaged to the backlog, so I've had to prioritize this PR likewise. Once 2.0 settles, I'll come back to this PR.

Given where we're at, this feature probably won't make it into the 2.0 release, but hopefully we can get it into the 2.1 release nice and early to start testing it in the wild.

**Comment by bricelam** [comment]
Picking this up again now that we've branched for 2.0. The improvements look good--looks like you found a few leaks. I'll run the EF Core tests against it an debug.

**Comment by bricelam** [comment]
I'm taking a different approach to debug the EF Core failures: Explicitly call `sqlite3_close` (throwing if it fails) in the ***current*** codebase. This will let me fix the problems there *before* testing it against this PR.

**Comment by bricelam** [comment]
I got to the bottom of the issue we were seeing. If a connection got finalized before a reader, the connection was left open. Updating to use `sqlite3_close_v2` (in #386) has resolved the issue.

**Comment by bricelam** [comment]
Superseded by #388

**Pull request closed without merging**
