### PR TITLE
Skip NativeLibraryLoader on non-Windows platforms

### LINKED ISSUE #101: Doesn't load native library on OS X Core CLR
`dnvm install -u latest -r coreclr`

On CoreCLR for OS X, NativeLibraryLoader cannot import "api-ms-win-core-libraryloader-l1-1-0".

```
DllNotFoundException: Unable to load DLL 'api-ms-win-core-libraryloader-l1-1-0': The specified module could not be found.
```

### PR DESCRIPTION
**Pull request by natemcmaster**
Fix #101

### CODE REVIEW

**Comment by bricelam** [comment]
Can you replace [the code in NativeLibraryLoader](https://github.com/aspnet/Microsoft.Data.Sqlite/blob/dev/src/Microsoft.Data.Sqlite/Utilities/NativeLibraryLoader.cs#L97-L100) instead?

**Comment by bricelam** [comment]
Or does it fail before that because it tries to JIT the P/Invoke methods?

**Comment by natemcmaster** [comment]
It fails because of https://github.com/aspnet/dnx/issues/2442

**Comment by bricelam** [comment]
Hmm, given that the DNX codepaths here are just temporary anyway... :shipit:

**Pull request merged**
