### PR TITLE
Support SQLite transaction types

### PR DESCRIPTION
**Pull request by natemcmaster**
Fix https://github.com/aspnet/Microsoft.Data.Sqlite/issues/205

### CODE REVIEW

**Comment by bricelam** [comment]
@divega Are there similar patterns on other providers that we should be following?

**Comment by bricelam** [comment]
I dug into this a bit more, and I think we have a bug around `IsolationLevel.Serialzable`. Here is how I think the isolation levels should be translated to SQLite.

IsolationLevel | SQL
-------------- | ---
ReadCommitted | PRAGMA read_uncommitted=0; BEGIN;
ReadUnommitted | PRAGMA read_uncommitted=1; BEGIN;
Serializable | PRAGMA read_uncommitted=0; BEGIN IMMEDIATE;

I'm not sure how `BEGIN EXCLUSIVE` maps (possibly `RepeatableRead`), but we can punt on this.

**Comment by natemcmaster** [comment]
Would be nice to have a test for the bug. Using internal email powers to see if we can reproduce the potential bug (and the fix) in IsolationLevel.Serializable

**Comment by bricelam** [comment]
I also started writing some functional tests in [bricelam:txtst](https://github.com/aspnet/Microsoft.Data.Sqlite/compare/dev...bricelam:txtst) to make sure we're not braking the `IsolationLevel` semantics.

**Comment by natemcmaster** [comment]
Close in favor of #213

**Pull request closed without merging**
